linters:
  disable:
    - interfacer
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

  enable-all: true

issues:
  exclude:
    - unused-parameter