linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - cyclop
    - dupword
    - wsl
    - varnamelen
    - usestdlibvars
    - unparam
    - revive
    - prealloc
    - misspell
    - gocyclo
    - funlen
